import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiderBar from "./components/Sidebar";
import Righbar from "./components/Rightbar";
import Footerbar from "./components/Footerbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen justify-between md:flex-row`}
      >
        <SiderBar />

        <div className="flex-2">{children}</div>

        <Righbar />

        <Footerbar />
      </body>
    </html>
  );
}
